apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg
resources:
  - resources/ns.yaml
helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    version: 0.27.0
    releaseName: cnpg
    namespace: cnpg
    includeCRDs: true
    valuesFile: values.yaml
