apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: k8s-monitoring
    repo: https://grafana.github.io/helm-charts
    version: 3.7.1
    releaseName: monitoring
    namespace: monitoring
    includeCRDs: true
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-production.yaml
patches:
  - path: ../../base/patches/node-exporter.yaml
    target:
      kind: DaemonSet
      name: monitoring-node-exporter
