apiVersion: 1
deleteRules:
  - orgId: 1
    uid: fbe074e7-0f0b-52ce-885d-bd45fa519f0f
  - orgId: 1
    uid: 9fa95258-6f0f-5a29-88ea-c37685b5307b
  - orgId: 1
    uid: b100c587-97a5-5a91-9090-f5c177717ce3
  - orgId: 1
    uid: bbdf214b-0bd3-53e5-87e9-b1a7eeecb8fe
  - orgId: 1
    uid: 25d7b969-35e5-5745-9b3d-2ac6ddba5a8a
  - orgId: 1
    uid: 0204686a-12de-55c4-aa4a-f39bfbc8a3d2
  - orgId: 1
    uid: 843e1e86-570e-53b5-a693-1f564e19e8d4
  - orgId: 1
    uid: ede26137-5983-57bb-bb72-5a658f435c09
  - orgId: 1
    uid: 0c13b6d0-47ce-57ef-9eb2-1d44d52d768f
  - orgId: 1
    uid: 04dd7cf1-96f4-5873-9d91-d96bccaefec8
  - orgId: 1
    uid: 4ff02394-8ae1-5cfc-b282-c8763985505b
  - orgId: 1
    uid: cc469ed2-16f6-5ac0-9fd7-697b5f23de07
  - orgId: 1
    uid: 0f54c939-7a86-5f37-88ad-7a74c0977418
  - orgId: 1
    uid: 405408dc-8fce-50e8-9b7b-51065851ce41
  - orgId: 1
    uid: 9f5d05a5-e4ec-54e8-baf9-5ca68baf2f49
  - orgId: 1
    uid: 055aca05-7861-5d0e-ae04-9b841261dc9f
  - orgId: 1
    uid: 71e9d6dc-0d39-5187-8ced-04d27190a64f
  - orgId: 1
    uid: c4278fd0-ad91-50c8-933b-052d8c83e029
  - orgId: 1
    uid: 31c80813-689d-55eb-9b0b-fa10cc0e8af0
  - orgId: 1
    uid: 4f09859f-e5c3-50d1-bdca-6a8991790b12
  - orgId: 1
    uid: b8097ea5-893a-5b74-8498-a1b31cb24c73
  - orgId: 1
    uid: cd3f16db-a5c3-5acb-8cde-83e3636e3bf1
  - orgId: 1
    uid: 270ea9f9-f5cd-51ca-a08c-93f8990cd483
  - orgId: 1
    uid: 431a95d3-d33a-5f84-b93b-f259a7123646
  - orgId: 1
    uid: 2d02fee6-6012-5039-a394-331778d7ce67
  - orgId: 1
    uid: a7a21eb2-2238-5654-8eb2-4fd679615471
  - orgId: 1
    uid: 20c7ba2b-86ba-5cd4-8688-41c14465f1ea
  - orgId: 1
    uid: 14f9cc9c-bdeb-5eae-ad04-7f962a835226
  - orgId: 1
    uid: 50948ecd-924f-5c45-bf7d-621078e7d85d
  - orgId: 1
    uid: 8c3b1f8b-747c-5385-8f8f-ef6442428c94
  - orgId: 1
    uid: af3d8453-6236-51cf-9490-c00686b22ff6
  - orgId: 1
    uid: 37f01052-3763-5bf5-853b-fb9f04027899
  - orgId: 1
    uid: 2af28bab-b462-5e1c-856f-5478efb7b1c4
  - orgId: 1
    uid: 2a7c303b-d1f5-51d2-a6c3-2c3e722fe8c4
  - orgId: 1
    uid: ceaea426-8c14-5418-8239-15ab54dc4455
  - orgId: 1
    uid: d0fcbf1a-8494-53ad-bfe5-5bd771779f4c
  - orgId: 1
    uid: 3d9ed0de-c7b1-5118-aea8-9566579d70e5
