apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
  - resources/ns.yaml
  - resources/ingr.yaml
  - resources/cert.yaml
configMapGenerator:
  - name: grafana-dashboards-node-exporter
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Node Exporter
    files:
      - node-exporter.json=assets/node-exporter/dashboard.json
  - name: grafana-dashboards-kube-state-metrics
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Kube State Metrics
    files:
      - kube-state-metrics.json=assets/kube-state-metrics/dashboard.json
  - name: grafana-rules
    options:
      disableNameSuffixHash: true
      labels:
        grafana_alert: "1"
    files:
      - node-exporter-rules.yaml=assets/node-exporter/rules.yaml
      - kube-state-metrics-rules.yaml=assets/kube-state-metrics/rules.yaml
      - delete-rules.yaml=assets/delete-rules.yaml
