apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
  - resources/ns.yaml
  - resources/ingr.yaml
  - resources/cert.yaml
configMapGenerator:
  - name: grafana-dashboards-node-exporter
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Node Exporter
    files:
      - node-exporter.json=assets/node-exporter/dashboard.json
  - name: grafana-rules
    options:
      disableNameSuffixHash: true
      labels:
        grafana_alert: "1"
    files:
      - node-exporter-alerting-rules.yaml=assets/node-exporter/alerting-rules.yaml
      - node-exporter-recording-rules.yaml=assets/node-exporter/recording-rules.yaml
