apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
  - resources/ns.yaml
  - resources/ingr.yaml
  - resources/cert.yaml
configMapGenerator:
  - name: grafana-dashboards-infrastructure
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Infrastructure
    files:
      - node-exporter.json=assets/dashboards/node-exporter.json
