apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-error-pages
spec:
  selector:
    matchLabels:
      app: traefik-error-pages
  template:
    metadata:
      labels:
        app: traefik-error-pages
    spec:
      containers:
        - name: nginx
          image: nginx:1.29.3@sha256:553f64aecdc31b5bf944521731cd70e35da4faed96b2b7548a3d8e2598c52a42
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 2
            periodSeconds: 2
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/conf.d
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: conf
          configMap:
            name: traefik-error-pages-conf
        - name: html
          configMap:
            name: traefik-error-pages-html
