apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 10.4.3
    releaseName: grafana
    namespace: grafana
    includeCRDs: true
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-production.yaml
patches:
  - path: patches/ingr.yaml
    target:
      kind: IngressRoute
      name: grafana
  - path: patches/cert.yaml
    target:
      kind: Certificate
      name: grafana
