apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: n8n
    repo: oci://8gears.container-registry.com/library
    version: 2.0.1
    releaseName: n8n
    namespace: n8n
    includeCRDs: true
    valuesFile: ../../base/values.yaml
    additionalValuesFiles:
      - values-production.yaml
  - name: cluster
    repo: https://cloudnative-pg.github.io/charts
    version: 0.5.0
    releaseName: n8n-cnpg-cluster
    namespace: n8n
    includeCRDs: true
    valuesFile: ../../base/values.cnpg.yaml
patches:
  - path: patches/ingr.yaml
    target:
      kind: IngressRoute
      name: n8n
  - path: patches/cert.yaml
    target:
      kind: Certificate
      name: n8n
