apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n
resources:
  - resources/ns.yaml
  - resources/ingr.yaml
  - resources/cert.yaml
configMapGenerator:
  - name: n8n-hooks
    options:
      disableNameSuffixHash: true
    files:
      - assets/hooks/auth.js
