destinations:
  - name: mimir
    type: prometheus
    url: http://mimir-gateway.mimir.svc.cluster.local/api/v1/push
    tenantId: k8s-nas
  - name: loki
    type: loki
    url: http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push
    tenantId: k8s-nas

# Features
clusterMetrics:
  enabled: true
  cadvisor:
    enabled: false
  kube-state-metrics:
    metricsTuning:
      useDefaultAllowList: false
  kubelet:
    enabled: false
  kubeletResource:
    enabled: false
  node-exporter:
    metricsTuning:
      useDefaultAllowList: false
  windows-exporter:
    deploy: false
    enabled: false

clusterEvents:
  enabled: true

nodeLogs:
  enabled: true

podLogs:
  enabled: true

prometheusOperatorObjects:
  enabled: true
  crds:
    deploy: true

# Collectors
alloy-metrics:
  enabled: true

alloy-singleton:
  enabled: true

alloy-logs:
  enabled: true
